name: Deploy Website


on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HTML Validation
        run: |
          npm install -g htmlhint
          htmlhint website/**/*.html

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Validate Key
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
            chmod 600 key.pem
            ssh-keygen -l -f key.pem
        
      - name: Test SSH Connection
        run: |
             ssh -vvv -o StrictHostKeyChecking=no \
             ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
             "echo 'Connection successful!'"
       
      - name: Clean Server Directory
        run: |
               ssh -o StrictHostKeyChecking=no -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo '$SUDO_PASSWORD' | sudo -S rm -rf /opt/lampp/htdocs/* && echo '$SUDO_PASSWORD' | sudo -S mkdir -p /opt/lampp/htdocs"

        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}  

      - name: Deploy
        run: |
            rsync -avz --delete -e "ssh" \
              ./website/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/lampp/htdocs/

      - name: Reload Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo /opt/lampp/lampp reloadapache"